/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>

#include "tcMenuAdaFruitGfx.h"
#include <RuntimeMenuItem.h>

// all define statements needed
#define DISPLAY_VARIABLE gfx
#define DISPLAY_TYPE Adafruit_ST7789
#define DISPLAY_CONFIG 
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
#define DISPLAY_RESET_PIN -1
#define DISPLAY_CS_PIN -1
#define DISPLAY_RS_PIN A4
#define DISPLAY_DATA_PIN -1
#define DISPLAY_CLOCK_PIN -1
#define DISPLAY_ROTATION 3
#define PULLUP_LOGIC true
#define INTERRUPT_SWITCHES true
#define SWITCH_IODEVICE 
#define ENCODER_PIN_A PA10
#define ENCODER_PIN_B PC13
#define ENCODER_PIN_OK PC15

// all variables that need exporting
extern Adafruit_ST7789 gfx;
extern AdaColorGfxMenuConfig gfxConfig;
extern AdaFruitGfxMenuRenderer renderer;

// all menu item forward references.
extern AnalogMenuItem menuLFO1Depth;
extern AnalogMenuItem menuLFO1Speed;
extern EnumMenuItem menuLFO1Parameter;
extern BooleanMenuItem menuLFO1LFOActive;
extern BackMenuItem menuBackLFO1;
extern SubMenuItem menuLFO1;
extern AnalogMenuItem menuSettingsNewAnalogItem;
extern AnalogMenuItem menuSettingsMIDIChannel;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern ActionMenuItem menuStore;
extern TextMenuItem menuName;
extern EnumMenuItem menuType;
extern const ConnectorLocalInfo applicationInfo;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onLFO1Active(int id);
void CALLBACK_FUNCTION onLFO1ParameterChange(int id);
void CALLBACK_FUNCTION onLFO1SpeedChange(int id);
void CALLBACK_FUNCTION onLFODepthChange(int id);
void CALLBACK_FUNCTION onMidiChange(int id);
void CALLBACK_FUNCTION onNameChange(int id);
void CALLBACK_FUNCTION onStore(int id);
void CALLBACK_FUNCTION onTypeChange(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
