/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuTfteSpi.h"
#include <graphics/MenuTouchScreenEncoder.h>
#include <ScrollChoiceMenuItem.h>
#include <BaseDialog.h>
#include <tcMenuVersion.h>
//#include "neon8.h"

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // contains app name and ID

// Global variables that need exporting

extern TFT_eSPI tft;
extern TfteSpiDrawable tftDrawable;
extern GraphicsDeviceRenderer renderer;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

extern AnalogMenuItem menuSettingsMIDIChannel;
extern BackMenuItem   menuBackSettings;
extern SubMenuItem    menuSettings;
extern ActionMenuItem menuStoreAll;
extern AnalogMenuInfo minfoCtrl1;
extern AnalogMenuInfo minfoCtrl2;
extern AnalogMenuItem menuCtrl2;
extern AnalogMenuItem menuCtrl1;
extern AnalogMenuItem menuEffect;
extern AnalogMenuItem menuDry;
extern EnumMenuItem   menuPedal;
extern AnalogMenuItem menuPreset;
extern ActionMenuItem menuPRESET;

extern ScrollChoiceMenuItem menuProgram;

// Provide a wrapper to get hold of the root menu item
inline MenuItem& rootMenuItem() { return menuPRESET; }

void CALLBACK_FUNCTION onName(int id);
extern TextMenuItem menuName;

void CALLBACK_FUNCTION onCtrl1(int id);
void CALLBACK_FUNCTION onCtrl2(int id);
void CALLBACK_FUNCTION onDry(int id);
void CALLBACK_FUNCTION onEffect(int id);
void CALLBACK_FUNCTION onPedal(int id);
void CALLBACK_FUNCTION onPresetMode(int id);
void CALLBACK_FUNCTION onPreset(int id);
void CALLBACK_FUNCTION onSettingsMIDIChannel(int id);
void CALLBACK_FUNCTION onStoreAll(int id);

int fnProgramRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);

#endif // MENU_GENERATED_CODE_H
